# Generated by Django 5.2.8 on 2026-02-07 17:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('simulation_count', models.IntegerField(default=0)),
                ('rating_score', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('last_simulation_time', models.DateTimeField(blank=True, null=True, verbose_name='Последняя симуляция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-rating_score'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_type', models.CharField(max_length=50, verbose_name='Тип симуляции')),
                ('energy', models.FloatField(blank=True, null=True, verbose_name='Энергия (ТэВ)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('simulation_results', models.JSONField(blank=True, default=list, help_text='Список обнаруженных частиц и событий', verbose_name='Результаты столкновения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запуск симуляции',
                'verbose_name_plural': 'Запуски симуляций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-rating_score'], name='accounts_us_rating__250ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-simulation_count'], name='accounts_us_simulat_8e2843_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationlog',
            index=models.Index(fields=['user', '-created_at'], name='accounts_si_user_id_93fe85_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationlog',
            index=models.Index(fields=['-created_at'], name='accounts_si_created_0c0c99_idx'),
        ),
    ]
